siteName: Art by Agnes Aasmaa
productionUrl: agnesita.pages.dev
languages:
  - code: en
    name: English
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: true
    isWebsiteDefault: true
collections:
  - articles
