siteName: Art by Agnes Aasmaa
productionUrl: https://agnesita.pages.dev
logo: /_images/logo-icon.webp
languages:
  - code: en
    name: English
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: true
    isWebsiteDefault: true
collections:
  - articles
